name: Test
on: workflow_dispatch
jobs:
  run_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: good-bona-app
    steps:
      - name: Get repo
        uses: actions/checkout@v3

      - name: Install Angular CLI
        run: npm install -g @angular/cli@17.0.0

      - name: Install dependencies
        run:  npm ci

      - name: Test app
        run: |
          echo "A second message"
          ng test --no-watch --source-map=false --browsers=Chrome

