name: Test
on: workflow_dispatch
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print console
        run: | 
          echo "A initial message"
          cd good-bona-app/

