name: Test
on: workflow_dispatch
jobs:
  run_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: good-bona-app
    steps:
      - name: Get repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run:  npm ci

      - name: Test app
        run: |
          cd good-bona-app/
          echo "A second message"
          npm run test

